### ISSUE TITLE
Bug report: No backups were saved...

### ISSUE THREAD

**Issue by MblaxxHD** [TechnicallyCoded/Inventory-Rollback-Plus#125]
### Bug description:
We have a current problem about the backups not saving on any actions that are in the options of the Restore 

### Server details:
 - Server type & version: 3726-Spigot-514cf03-5ee3419 (MC 1.19.4) (Implementing API version 1.19.4-R0.1-Snapshot)
 - InventoryRollbackPlus version: 1.6.9

### How to reproduce:
N/A
### What was expected:
N/A

### Screenshots, logs & other:
https://pastebin.com/0btcVKYE

#### **Additional info:**
N/A

**Comment by TechnicallyCoded** [comment]
Per your logs `java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors`

Problem: It seems as though SSL is not supported or correctly setup for your SQL server.
Potential fix:
```
In config.yml and set one or all of the following options as such
  use-SSL: false
  verifyCertificate: false
  allowPubKeyRetrieval: true
```
This basically disables SSL for IRP but it's not storing passwords so that's not a huge security issue.

**Comment by MblaxxHD** [comment]
can i just reload the plugin or just restart the server?

**Comment by MblaxxHD** [comment]
Now i have this problem after reloading the config
https://pastebin.com/VdnCnXnB
