### ISSUE TITLE
Request for Reposting Authorization

### ISSUE THREAD

**Issue by postyizhan** [TechnicallyCoded/Inventory-Rollback-Plus#161]
Hello! I would like to repost your plugin `Inventory-Rollback-Plus` to the forum https://www.minebbs.com/. I will make sure to indicate the author and source. I hope you can agree to this.

**Comment by TechnicallyCoded** [comment]
Short answer: no.

If I don't post my plugin somewhere, it's that I don't see the point to place it there. There is no obligation for it to be on a platform I did not chose. I will request the deletion and report abuse against anyone who reposts my work on any platform. Should platforms fail to comply, I usually take it up with domain authorities which usually gets them back on track since they risk losing their entire business.

**Comment by postyizhan** [comment]
I sincerely apologize if my previous message seemed impolite. I spoke with a friend, and they mentioned that my tone might have been off. Since English isn't my first language, I didn't realize it might come across that way. Thank you for your understanding.
