### ISSUE TITLE
Feature-Request (Cached NBT, Paper chunk loading and more async calls)

### ISSUE THREAD

**Issue by Ryoyo2** [TechnicallyCoded/Inventory-Rollback-Plus#3]
Greetings,
Would you consider merging this into your fork? I'm honestly not too familiar with Github/Coding and the difficulties involved, however these improvements might help a lot with all the performance issues of the plugin:
https://github.com/danjono/Inventory-Rollback/pull/38

Another interesting feature with a lot less priority could be this one:
https://github.com/danjono/Inventory-Rollback/issues/34

Thank you for maintaining this plugin since it's the only one that actually works.

**Comment by TechnicallyCoded** [comment]
Hey thanks for bringing this up.

I will definitely take a hard look at this and see what I can do. Async calls, paper chunk loading and all that do seem pretty important.

However I should note that the latest version I pushed to spigot is mostly async when it comes to saving from what I remember. I'll have a better look at that though because about half of the update was taking danjono's dev branch and adding to the main plugin after testing it a bunch for potential errors. I didn't really touch the saving procedures myself.

**Comment by LucidAPs** [comment]
+1 for these improvements.

**Comment by TechnicallyCoded** [comment]
You probably already noticed that in the latest update, the death reasons are improved but I am putting this here anyway for anyone who would stumble upon this issue tracker and wonder what has been done.

I have been looking into async chunk pre-loading so I think this could be done soon.

I don't think I will just use the pull request though, since we are working on 2 different code bases but I will add what I can.

**Comment by TechnicallyCoded** [comment]
Issue is inactive and most features have been added.
