### ISSUE TITLE
Issue | Performance impact.

### ISSUE THREAD

**Issue by hemanth4121** [TechnicallyCoded/Inventory-Rollback-Plus#35]
Hey, this is an issue we're facing on our network during peak hours where actions from inventory rollback caused lag spikes/tps dip.
Here are the attached spark timings for reference.
https://spark.lucko.me/rdEhT1PY2i
https://spark.lucko.me/njsPI0MUQV
It also was recommended by one of my staff members to add in an async onjoin save inventory task.

**Comment by TechnicallyCoded** [comment]
one of your timing reports show that some of your tick lag is originating from player heads. The lag related to IRP (using MySQL) has been fixed in the dev branch, however I must wait to see if this is stable enough to release :)

You are welcome to compile that version and give feedback related to any issues you encounter!

**Comment by TechnicallyCoded** [comment]
An update resolving your issue has been pushed to spigot :)

Thanks for your report!
