### ISSUE TITLE
Support: [Server is Lagging bcz From Inventory Roll Back Plus]

### ISSUE THREAD

**Issue by Shivam9864op** [TechnicallyCoded/Inventory-Rollback-Plus#37]
*Ask your question here*
InventoryRollbackPlus::Event: m.d.i.l.EventLogs (PlayerChangedWorldEvent)count(4)  total(0.02% 0.325s, 0.04% of tick)avg(81.34ms per - 0.02ms/0.00 per tick

taking too many ticks.. 
i did t found anything to disable the world event inventory please help me

**Comment by TechnicallyCoded** [comment]
I recently received a report from someone else with concrete data to work with citing exactly where some lag issues could be coming from.

I am going to guess that you are currently using the plugin using a MySQL database. The issue with the current release is that past backups are not cleared asynchronously therefore creating lag spikes when a save happens if you have a slower than ~5ms response time between the database and the database location.

**Comment by Shivam9864op** [comment]
sorry for the late reply.. yes I was using MySQL...

**Comment by Shivam9864op** [comment]
how can i download dev version??

**Comment by TechnicallyCoded** [comment]
An update was released with performance improvements ^^. Please test it and inform me if this aided your situation. 

Issue will be closed in about a week if there is no further reply.
