### ISSUE TITLE
What are the conditions of the license?

### ISSUE THREAD

**Issue by OLEGSHA** [TechnicallyCoded/Inventory-Rollback-Plus#60]
In `LICENSE`, there does not seem to be any unambiguous list of rights granted by the license and conditions enforced by the license. What makes your license different from MIT?

Insofar, the license asserts copyright, defines two terms, explains the relationship of this fork with the original plugin, warns about the possibility of license changes, and entitles certain individuals to additional rights.

If you meant an "All rights reserved"-style EULA, please at least include this statement somewhere in the license. Better yet, please list the specific rights you grant to end users, and conditions you expect these end users to abide by. (You might want to be specific because, for example, the right to study the work and use gained knowledge in own works is not protected under copyright, and if you wish to prohibit others from studying your code, you should ask the end user to waive this right explicitly by accepting the license.)

Finally, it is not clear how license changes are supposed to affect end users. Either the new license is in effect for copies already downloaded, or it is only applied to newer releases. If I obtain version 1.6.4 under your current terms, and then for 1.6.5 you update the terms, do I retain the old license for 1.6.4, or is it retroactively applied to all users?

_P.S., a personal question - why not MIT/GPL?_

**Comment by TechnicallyCoded** [comment]
All rights reserved is a general thing you put on your work if you don't want people to copy what you have created. Every single website references this but given that I do mention specific users have the right to use my edits or that any can fork the project in order to contribute back to the IRP repo, I can't say that. I am not a lawyer and I don't pretend to be. 
I mention that it is up the end user to stay up to date with the license changes.

> What makes your license different from MIT?
You can't use what I have wrote for any reason even if your source is open too.
The source that this project is forked from still keeps the same license which means you can use that code without issue since I have no way of protecting something that's already under MIT. Not that I would want to, I am only protecting my edits.

If there were to be a legal battle I have no idea what would happen but in "normal people" terms: I am holding onto the rights to my edits, don't republish that anywhere, unless it's solely to contribute to this repo or given express permission to do so.

> Why not MIT/GPL? 
Cuz I chose to? I am keeping the source public because I firmly believe that people shouldn't really trust random plugins without taking a look at what it's doing to your server. That doesn't mean I am giving it away for people to shove into something else and call it a day. As I also stated, the license will probs become GPL once I decide to no longer maintain this. However that isn't legally binding.
