### ISSUE TITLE
Bug report: No Shulkers

### ISSUE THREAD

**Issue by Specthra** [TechnicallyCoded/Inventory-Rollback-Plus#63]
**### Bug description:**
Shulkers do not appear in user backups

**### Server details:**
 - Server type & version: 
 [16:10:36 INFO]: This server is running Purpur version git-Purpur-1504 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: cb1a636 on HEAD)
[16:10:36 INFO]: You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads
[16:10:36 INFO]: Previous version: git-Purpur-1428 (MC: 1.17.1)

 - InventoryRollbackPlus version: 
 [16:10:59 INFO]: [InventoryRollbackPlus] 
Plugin:
  Running InventoryRollbackPlus v1.6.5
Authors:
  - Maintained/updated by: TechnicallyCoded
  - Original author: danjono

**Update link:**
  https://www.spigotmc.org/resources/inventoryrollback-plus.85811/

**### How to reproduce:**
Updated plugin from 1.17 to 1.18. The database was linked and everything appears except the shulkers

**### What was expected:**
Being able to have the shulkers to restore them in the users' inventories

**### Screenshots, logs & other:**
https://prnt.sc/26e0oth
https://prnt.sc/26e0pcu

**Comment by TechnicallyCoded** [comment]
Are there any error logs?

**Comment by Specthra** [comment]
No, no errors on console 
It's as if they were never saved

**Comment by TechnicallyCoded** [comment]
Well, are the changes actually in the file and is the database marked as enabled?

**Comment by Specthra** [comment]
yes, everything is there but not the shulkers.

**Comment by TechnicallyCoded** [comment]
I feel real stupid right now, that answer was supposed to be for another issue...
Do backups *created* in 1.18 appear normally in 1.18?

**Comment by Specthra** [comment]
Saved in version 1.17.1
Server was updated from that version to 1.18.1

A backup was made in case something goes wrong, it was linked to the database and the shulkers do not appear in the inventory backups

**Comment by TechnicallyCoded** [comment]
It's normal for certain items to not work across versions. The way that items are stored to a string of characters to later be decoded back into items is very much version dependent. Could you try running a force backup of the player's inventory now that they are in 1.18? If the items don't appear for the same version I am worried, otherwise, unfortunately there isn't much we can do about it other that creating translation layers for each version which isn't worth the time for backups. 
Also, if the plugin is working normally, old backups, even if incompatible, should not be damaged from trying to be viewed in another version. If you copy the database or config file entry to a 1.17 server all the data should still be available.

**Comment by TechnicallyCoded** [comment]
I'll re-open if 1.18 saves don't work in 1.18, I get discord pings for these messages even if it's closed so dw. However, I need to cleanup what I think should be resolved. Have a nice day :)
