### ISSUE TITLE
Support: SQL Communications Link Failure

### ISSUE THREAD

**Issue by nicholasveronico** [TechnicallyCoded/Inventory-Rollback-Plus#98]
*Ask your question here*

Hello! I’ve been seeing this error recently spam my console without any pattern. I am on IRP 1.6.7 and my server version is Purpur 1.18.2

-redacted-

**Comment by TechnicallyCoded** [comment]
Seems like a port is not open or you are using the wrong IP. Basically it has no contact to anything.

**Comment by nicholasveronico** [comment]
That's the issue. The connection to the database is completely fine. This has happened in the past with one of our other plugins using SQL. The developer implemented a keep-connection interval to ensure it doesn't randomly stop responding. Is something like this possible?

**Comment by TechnicallyCoded** [comment]
So a system to auto-reconnect? Because a keep-alive is exactly what it's doing an hence why it can detect that the connection failed. 

Secondly, the fact that the connection is failing between 2 servers is more problematic than you might think. If you are home hosting, that is extremely unreliable compared to even the cheapest cloud hosting options. 

To put in perspective, it's like using kitchen tools to perform a surgery.. the level of attention to detail for the equipment being used is basically non-existent in consumer products. Consumers want cool things that run fast, therefore, rebooting your router and internet experiencing micro-cuts is quite expected for residential internet and equipment. Companies, on the other hand, want efficient, fast, and above all, reliable equipment that will run for 10 years with minimal intervention.

**Comment by nicholasveronico** [comment]
Hello. I just wanted to touch base again regarding this issue. Our network has noticed one other plugin causing issues, and it looks like the issue was rooted in the SQL driver version. Does InventoryRollbackPlus use SQL driver version 5.7?

**Comment by TechnicallyCoded** [comment]
There is no SQL driver provided with the plugin. It is expected that spigot/paper already has one. Which to my knowledge, has been included since 1.8... More recently, in 1.19, the sql driver included is 8.0.x If your server software is out of date, you should update.

This information could be checked by just looking at the pom.xml file, that has all dependencies.

![image](https://user-images.githubusercontent.com/29813490/181716040-1eb7ed3d-4bbe-4ccc-8576-1df106dd9113.png)

**Comment by TechnicallyCoded** [comment]
Closing due to a lack of follow-up

**Comment by lukemango** [comment]
also experiencing this issue, server literally doesn't get past being up for more than 30 seconds without hard crashing

**Comment by arenmarsden** [comment]
> 

same, it's like 15-30 seconds and it just dies. exact same issue

**Comment by gurrrrrrett3** [comment]
hey, my server just had this issue, server will not stay up for more than 20 seconds before it hard crashes
